### ISSUE TITLE
Facebook and Google Plus share button not working

### ISSUE THREAD

**Issue by jamesy829** [hermango/shareable#13]
I have added facebook, twitter, and google plus button onto a page but only twitter would work properly.

If I click on the Facebook like button, it would quickly show a div and hide it right away

If I click on the Twitter tweet button, an overlay would open, which is working properly

If I click on the Google +1 button, it would render quickly then errors out and show the ! triangle mark.

No errors are showing in the console except a warning

Invalid App Id: Must be a number or numeric string representing the application id. all.js:54

**Comment by hermango** [comment]
Hi James, please copy and paste the code you're using to render the buttons. Also, if you generated a local copy of the config file 'shareable.rb', can you paste the part: 

```
##############
#facebook
##############
config.app_id = '' 
```

Have you made sure that app_id has a value and that value is a string (enclosed in quotation marks)?

**Comment by hermango** [comment]
I can't recreate the issue. Is your app using the latest gem version 1.1.3? Also if you're using Turbolinks, try setting config.turbolinks to true ([more about that](https://github.com/hermango/shareable#turbolinks)). If you can share your code or page source or link me to a live site, I can help you better. Regardless, if you could update this issue, I'd appreciate it. I'd like to know what's causing the issue, so I can add a catch in the code to prevent it.

**Comment by jamesy829** [comment]
I am currently directly using the iframe provided by Facebook and JS code provided by Google, I will switch back and if issue does occur, I will reopen the issue and post the errors

**Comment by jamesy829** [comment]
When I use the `google_plus` button, I would get this error

![screen shot 2014-07-20 at 3 25 39 pm](https://cloud.githubusercontent.com/assets/334169/3638336/c2591676-1043-11e4-83de-60fa53789bfd.png)

My config for google plus button

  ###############
  ##google_plus
  ###############
  config.annotation='bubble' # 'none', 'bubble' or 'inline'. '' defaults to 'bubble'.
  config.align='' # 'left' or 'right'. '' defaults to 'left'.
  config.expand_to='' # comma separated list of 'top', 'right', 'bottom' and 'left'.
  config.callback=''
  config.onstartinteraction=''
  config.onendinteraction=''
  config.recommendations='true' # 'true' or 'false'. '' defaults to 'true'.

**Comment by jamesy829** [comment]
When I use the `facebook` button, I would not get any errors, but clicking 'like' button will show and hide the overlay very quickly.

My config for facebook button

  ###############
  ##facebook
  ###############
  config.app_id='1450818731838914' # required if using facebook button!
  config.send= 'false'
  config.layout='standard' # 'standard', 'button_count', 'button' or 'box_count'. '' defaults to 'standard'.
  config.show_faces='' # 'true' or 'false'. '' defaults to 'false'. Don't set to 'true', if kid_directed_site is also 'true'.
  config.action='' # 'like' or 'recommend'. '' defaults to 'like'.
  config.font=''
  config.colorscheme='' # 'light' or 'dark'. '' defaults to 'light'.
  config.ref=''
  config.share='true' # 'true' or 'false'. '' defaults to 'false'.
  config.kid_directed_site='' # 'true' or 'false'. '' defaults to 'false'. Facebook assumes your site is not kid friendly.

**Comment by hermango** [comment]
> Invalid App Id: Must be a number or numeric string representing the application id. all.js:54

This error is from Facebook and means Facebook can't validate the value in the app_id field. There can be multiple reasons for this error:
1. app_id is blank.
2. One or more of the configuration values you've passed to shareable have a mismatched quote. For example:

```
 config.title='Many men's moustaches tickle their noses.' 
```

The above is invalid because the apostrophe in "men's" has closed the string. Use double quotes when you need to use an apostrophe or do a string replace of quotes inside your text with the html ascii equivalents (&&#35;34; for double quote and &&#35;39; for single quote) before passing the value to shareable.
3. One or more of the configuration values you've passed to shareable are not string values. One way to check for this problem is to view the source code of your html page. You may find Rails has inserted trace code for the error.
4. You've written your own Facebook button and overridden shareable's default Facebook button code but your code has a syntax error in it.
5. You have some malformed HTML in your web page like an extra script tag.
6. Your version of the shareable gem needs to be updated.
7. You are running your application locally (localhost) and clicking the Like button. Try running on a public domain.

> If I click on the Google +1 button, it would render quickly then errors out and show the ! triangle mark.

This may happen when running your application locally. As far as I can tell, Google+ button won't work when sharing from localhost. If you run on a public domain, the button should work and you shouldn't see the red exclamation mark. If this is still not working live, please let me know. Also [check this thread for more info](https://productforums.google.com/forum/#!topic/webmasters/26AHJgn6uNY).

> If I click on the Facebook like button, it would quickly show a div and hide it right away

Ah! So this is a bug. Facebook Like button behavior [has changed](https://developers.facebook.com/docs/apps/upgrading) since the release of this gem. The [latest release (1.1.4) of shareable](https://github.com/hermango/shareable/releases/tag/v1.1.4) fixes this issue. Also if you copied the [original CSS from the README](https://github.com/hermango/shareable/commit/b6d8b0e8b23bde309b94b2b408905182ea354434), please [update your styling](https://github.com/hermango/shareable#styling-for-buttons). 

Thank you for reporting this issue, James. I'm closing this. If the problems persist after updating your gem to 1.1.4, please feel welcome to re-open it.

**Comment by sy-tian** [comment]
Hi, I update shareable to the lastest release(1.1.4), but Facebook Like problem still exists. And It's very inconsistently
