### ISSUE TITLE
Facebook Button Not Displaying

### ISSUE THREAD

**Issue by DavidDomzalski** [hermango/shareable#4]
Hey,

I just wanted to make you aware that I installed the gem and it's fantastic. However, the Facebook button is not displaying for me. I'm sure how to display it. It doesn't work when I attempt to render all buttons or just the Facebook button specifically.

Thanks,

Dave

**Comment by hermango** [comment]
Hi Dave, 

Thanks for taking the time to write and for using the gem. Is this happening when running on localhost? After a while, the Facebook button will stop appearing when the js is called from a local env enough times. Facebook is monitoring and denying these requests. Kind of a pain for us when we develop but also out of our control.[Edit: turns out there's a fix. See below.] If this is happening on a production server, then I need to check on this.

Best regards,
Herman

Edit: There is now a fix to this issue. Check out this comment: https://github.com/hermango/shareable/issues/4#issuecomment-47410829

**Comment by squareleaf** [comment]
This is really good to know. The Facebook button stopped appearing for me locally on one of the projects I work on, and I could never figure out why. Mystery solved - thanks!!

**Comment by hermango** [comment]
Here is a fix to correct this problem of Facebook not appearing or if you get the warning message in Chrome console _"Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings.  It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."_ (assuming this problem is happening on your local development environment):

In your developer account on Facebook, select the App you're using for testing. Go to Settings.
![shareable-facebook](https://cloud.githubusercontent.com/assets/28847/3418949/5b1a653a-fe52-11e3-862f-8e933f9e045f.png)

On the Settings page: 
1) Click "Add Platform". 
2) Type "http://localhost:" and the port number you're running your Rails server on (usually 3000). If you're running <a href='http://pow.cx/'>pow</a> or have edited your /etc/hosts file to map your rails app to a domain other than localhost then adjust the value inputted in this field accordingly.

If you're not redirecting a public domain to localhost (as most of us won't be for developing) then be sure to leave the App Domains field blank. Otherwise this fix won't work.
