### ISSUE TITLE
Buttons do not display on paginate pages

### ISSUE THREAD

**Issue by LeoJavaAI** [hermango/shareable#5]
Hi,

The buttons display fine when the home page resolves,  but when you click on the 2 page it does not can someone shed some light on what the issue could be
http://bhaagbose.tk/

**Comment by hermango** [comment]
Hi Leo-g, Thanks for using this gem. I'm not sure that pagination has much to do with the problem because the buttons still appear on paginated pages for me sometimes, albeit arbitrarily. I ran your URL through the W3C validator and found some errors, such as duplicate "body" html tags: http://validator.w3.org/check?uri=http%3A%2F%2Fbhaagbose.tk%2F&charset=%28detect+automatically%29&doctype=Inline&group=0 

In testing shareable, I noticed the buttons are sensitive to html markup errors. So you may want to start there. What pagination gem and version of Rails are you using?

**Comment by LeoJavaAI** [comment]
Thank you for replying, I will check on the errors as you suggested.

I am using kaminari with rails 4

**Comment by hermango** [comment]
Issue in Rails 4 and Rails 3.2 apps using Turbolinks. See issue https://github.com/hermango/shareable/issues/6
