### ISSUE TITLE
rails 4

### ISSUE THREAD

**Issue by webalosarema** [hermango/shareable#6]
the links are not loading on rails 4 because of turbolinks  on link follow

**Comment by hermango** [comment]
Hi özgür, Thank you very much for finding and reporting this bug. According to https://github.com/rails/turbolinks/issues/119, the problem may be from Twitter (and the other buttons calling event.preventDefault()). Revision appearing soon will be Turbolinks compatible. 

Until then, if you want, you can overwrite the shareable Twitter button (as explained in the <a href='https://github.com/hermango/shareable/blob/master/README.md'>readme</a>) by doing the following:
1. In your html, add after the body tag:
   &lt;script src="//platform.twitter.com/widgets.js"&gt;&lt;/script&gt;
2. Create the file:
   app/views/shareable/_twitter.html.erb
   
   Into that file copy and paste:
   &lt;a href='http://twitter.com/share'
   class='twitter-share-button'
   data-url='<%= options[:url] %>'
   data-via='<%= options[:via] %>'
   data-text='<%= options[:text] %>'
   data-related='<%= options[:related] %>'
   data-count='<%= options[:count] %>'
   data-lang='<%= options[:lang] %>'
   data-counturl='<%= options[:counturl] %>'
   data-hashtags='<%= options[:hashtags] %>'
   data-size='<%= options[:size] %>'
   data-dnt='<%= options[:dnt] %>'&gt;Tweet&lt;/a&gt;

or add the button using the instructions at https://dev.twitter.com/docs/tweet-button and https://about.twitter.com/resources/buttons

I'm sorry for any inconvenience caused by this issue. The next update to shareable fixes turbolink related bugs.

If you need social buttons for an app that uses Turbolinks before the next update comes out, 
Nick Reed has written a list of workarounds to get Turbolinks working with social buttons: http://reed.github.io/turbolinks-compatibility

Update: The above fix for the Twitter button is in version 0.0.3. Out now.  Revision still on the way.

**Comment by hermango** [comment]
Turbolinks is now supported starting with version 1.1.3. Run 'bundle update' to get the latest gem. 

A couple of caveats to this solution however:
1. New configuration option _turbolinks_ has been added and must be set to boolean value **true**. This option is **false** by default.
2.  jQuery is required.

**If** this solution doesn't work for someone's particular setup (e.g. using pjax instead or don't want to use jQuery) then a new configuration option _button_only_ has been added. Setting this option to **true** suppresses output of javascript code for buttons. E.g.:

```
<%= render_shareable :facebook=>{:button_only=>true} %>
```

Someone can then include their own javascript fix. Though I imagine most projects using Rails, use Turbolinks and jQuery. So setting option _button_only_ should be less preferred.

Please see the section on [Turbolinks](https://github.com/hermango/shareable#turbolinks) for more details.
