### ISSUE TITLE
changing social icons

### ISSUE THREAD

**Issue by vjaykoogu** [hermango/shareable#7]
how about changing social icons ?

**Comment by hermango** [comment]
Hi Vijay,

I've updated the documentation with more details on customizing buttons. Please have a look at
https://github.com/hermango/shareable#customizing-buttons Since your question, I've added the option of static links to Shareable. Static links can be made into image links with any icons you'd like. I don't include the icon files with this gem because there's already a great variety of them available online. Hopefully there's enough hints in the above link to figure it out. If not, please let me know and I'll explain in more detail.

Also if you mean changing the icons of the javascript buttons then all of that's configurable. Please see the configuration file https://github.com/hermango/shareable/blob/master/lib/shareable/config.rb.

Thank you for your question.

**Comment by marcamillion** [comment]
There a way to use FontAwesome icons, instead of the stock ones, if it is included in my Rails app by default?
